BaseURL = "/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "北极狼徒"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true

[Author]
  Name = "Jerling"

[outputs]
  home = [ "RSS", "HTML" ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[Params]
  AuthorHomepage = "/"
  BottomIntroduce = "码农一枚 <br/> 混口饭吃"
  Description = "随便写写"
  Subtitle = "个人博客"
  Weibo = ""
  WeiboID = 123
  Twitter = ""
  GitHub = "Jerling"
  Facebook = ""
  LinkIn = ""
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true
  CreativeCommons = true
  MathJax = false

  [Params.GoogleAnalytics]
    ID = ""

  [Params.Disqus]
    ShortName = ""

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/post"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2
  [[Menu.Main]]
    Name = "收藏"
    URL = "/bookmark"
    Weight = 3
